services:
    api:
        container_name: passkeys-api
        image: passkeys-api:latest
        build: .
        env_file:
            - .env
        ports:
            - "${CONTAINER_PORT}:${CONTAINER_PORT}"
        platform: linux/arm64
